DROP TABLE IF EXISTS UNITS;
DROP TABLE IF EXISTS ENEMIES;
DROP TABLE IF EXISTS PLAYER;
DROP TABLE IF EXISTS TYPES;

CREATE TABLE PLAYER (
    ID SERIAL PRIMARY KEY NOT NULL,
    HEALTH INTEGER NOT NULL,
    TYPES NOT NULL);

CREATE TABLE UNITS (
    ID SERIAL PRIMARY KEY NOT NULL, 
    NAME VARCHAR(30) NOT NULL, 
    HEALTH INTEGER NOT NULL,
    DAMAGE INTEGER NOT NULL,
    ATTACK_RANGE INTEGER NOT NULL,
    TYPE1_ID VARCHAR NOT NULL
    TYPE2_ID VARCHAR NOT NULL
    TYPE3_ID VARCHAR NOT NULL);

CREATE TABLE ENEMIES (
    ID SERIAL PRIMARY KEY NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    HEALTH INTEGER NOT NULL,
    DAMAGE INTEGER NOT NULL,
    ATTACK_RANGE INTEGER NOT NULL);

CREATE TABLE TYPES (
    ID SERIAL PRIMARY KEY NOT NULL,
    NAME VARCHAR(15) NOT NULL,
    BUFF VARCHAR(30) NOT NULL);


